fix: FTBFS on Linux due to missing #include
> src/model/dsp/base/WowFlutter.h: In
> member function ‘float WhiteNoiseOsc::doWhiteNoise()’:
> src/model/dsp/base/WowFlutter.h:80:25:
> error: ‘arc4random’ was not declared in this scope